name: "playstation-box"
description: "Update a pinned gist to contain PlayStation stats"
branding:
  icon: "flag"
  color: "yellow"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: Run
      env:
        PSN_NPSSO: ${{ secrets.PSN_NPSSO }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      shell: bash
      run: python src/main.py
